---
- name: Add mysql group
  group:  name=mysql gid={{ mysql_gid }} state=present
- name: Add mysql user
  user: name=mysql uid={{ mysql_uid }} group=mysql state=present

- name: Create mysql_down_dir directory
  file: path={{ mysql_down_dir }} state=directory
- name: Create mysql_data_dir directory
  file: path={{ mysql_data_dir }}  owner=mysql group=mysql state=directory recurse=yes
- name: Create mysql_install_dir directory
  file: path={{ mysql_install_dir }} owner=mysql group=mysql state=directory recurse=yes
- name: Create mysql_sock directory
  file: path=/var/lib/mysql   owner=mysql  group=mysql state=directory recurse=yes

- name: Create bin_logs directory
  file: path={{ mysql_logs_dir }}   owner=mysql  group=mysql state=directory recurse=yes


- name: Insatall libaio package
  yum:  name=libaio state=present
- name: Download mysql package
  get_url:  url="{{ mysql_repo_url_prefix }}/{{ mysql_name }}"  dest={{ mysql_down_dir }}

- name: Tar mysql download package
  shell:  chdir={{ mysql_down_dir }}  tar xvf {{ mysql_name }}
- name:  Copy mysql_tar_dir to mysql_install_dir
  shell:  cp -r {{ mysql_down_dir }}/{{ mysql_tar_dir }}/* {{ mysql_install_dir }}

- name: Mysql init
  shell:  chdir={{ mysql_install_dir }} ./bin/mysqld --initialize --user=mysql --datadir={{ mysql_data_dir }} --basedir={{ mysql_install_dir }} --socket={{ mysql_sock }}
- name: Setup mysql environment
  template: src=templates/mysql.sh.j2 dest=/etc/profile.d/mysql.sh
- name: Source mysql environment
  shell:  source /etc/profile.d/mysql.sh

- name: Add mysql service
  shell:   cp {{ mysql_install_dir }}/support-files/mysql.server /etc/init.d/mysql
- name: Copy mysql Configure files
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf

- name: Start mysql service
  command:  /etc/init.d/mysql start
- name: Clear mysql download package
  shell: rm -rf {{ mysql_down_dir }}
